CREATE DATABASE t2;

use t2;

CREATE TABLE aluno (id int AUTO_INCREMENT PRIMARY KEY, 
nome VARCHAR(255) NOT NULL, idade int NOT NULL , 
email VARCHAR(255) NOT NULL, 
endereco VARCHAR(255) NOT NULL, 
cep VARCHAR(15), 
telefone VARCHAR(15), 
usuario VARCHAR(255) NOT NULL, 
senha VARCHAR(255) NOT NULL, 
curso VARCHAR(50) NOT NULL , 
observacoes VARCHAR(255) NOT NULL,  
ativo BOOLEAN NOT NULL  CHECK (ativo IN (TRUE, FALSE)));